# Generated by Django 4.2.23 on 2025-06-23 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingpersonreport',
            name='national_id',
            field=models.CharField(blank=True, help_text='National identification number (8-20 characters)', max_length=20, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(20)]),
        ),
        migrations.AddConstraint(
            model_name='missingpersonreport',
            constraint=models.UniqueConstraint(condition=models.Q(('national_id__isnull', False)), fields=('national_id',), name='unique_national_id'),
        ),
    ]
