# Generated by Django 4.2.23 on 2025-06-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_missingpersonreport_national_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingpersonreport',
            name='face_encoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
