# Generated by Django 4.2.23 on 2025-06-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_missingpersonreport_face_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationlog',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='action',
            field=models.CharField(max_length=10),
        ),
    ]
