# Generated by Django 4.2.23 on 2025-06-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reportmessage_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
